import math
num = float(input("Ingrese un número: "))
seno = math.sin(num)
coseno = math.cos(num)
tangente = math.tan(num)
raiz = math.sqrt(num)
logaritmo_n = math.log(num)
logaritmo10 = math.log10(num)
print("Seno:", seno)
print("Coseno:", coseno)
print("Tangente:", tangente)
print("Raíz:", raiz)
print("Ln:", logaritmo_n)
print("Log10:", logaritmo10)